export IMAGE=quay.io/ascend/vllm-ascend:nightly-releases-v0.23.0-a3
TODAY=$(date +%Y%m%d%H)
export NAME=glm5_2_w4a8_memcache_${TODAY}_stl
docker run -itd \
    --name $NAME \
    --privileged=true \
    --net=host \
    --shm-size=1024g \
    --device /dev/davinci0 \
    --device /dev/davinci1 \
    --device /dev/davinci2 \
    --device /dev/davinci3 \
    --device /dev/davinci4 \
    --device /dev/davinci5 \
    --device /dev/davinci6 \
    --device /dev/davinci7 \
    --device /dev/davinci8 \
    --device /dev/davinci9 \
    --device /dev/davinci10 \
    --device /dev/davinci11 \
    --device /dev/davinci12 \
    --device /dev/davinci13 \
    --device /dev/davinci14 \
    --device /dev/davinci15 \
    --device /dev/davinci_manager \
    --device /dev/devmm_svm \
    --device /dev/hisi_hdc \
    -v /usr/local/dcmi:/usr/local/dcmi \
    -v /usr/local/Ascend/driver/tools/hccn_tool:/usr/local/Ascend/driver/tools/hccn_tool \
    -v /usr/local/bin/npu-smi:/usr/local/bin/npu-smi \
    -v /usr/local/Ascend/driver/lib64/:/usr/local/Ascend/driver/lib64/ \
    -v /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info \
    -v /etc/ascend_install.info:/etc/ascend_install.info \
    -v /etc/hccn.conf:/etc/hccn.conf \
    -v /mnt/sfs_turbo/.cache:/root/.cache \
    -v /mnt/sfs_turbo/:/mnt/sfs_turbo/ \
    -v /mnt/sfs_turbo_glm5/:/mnt/sfs_turbo_glm5/ \
    -v $HOME/.claude:/root/.claude \
    -v $HOME/.anthropic:/root/.anthropic \
    -e CLAUDE_CONFIG_DIR=/root/.claude \
    -it $IMAGE bash
